### ISSUE TITLE
Cannot import "WarmUpLinearSchedule"

### ISSUE THREAD

**Issue by manueltonneau** [ThilinaRajapakse/simpletransformers#59]
Getting this error this morning and wasn't getting it yesterday while running:
`from simpletransformers.classification import ClassificationModel`.

The details of the error are as follows:

---> 30 `from transformers import AdamW, WarmupLinearSchedule`
     31 `from transformers import (`
     32   `  WEIGHTS_NAME,`

ImportError: cannot import name 'WarmupLinearSchedule'

Could this be linked with the launch of the v2.2 version of the transformers package yesterday?

**Comment by tsavinho** [comment]
I'm running into the same issue, and I can confirm that it is related to yesterday's release, a package downgrade to transformers 2.1.1 allowed me to run my code again.

**Comment by manueltonneau** [comment]
Same here! Thanks for the heads up though! :)

**Comment by ThilinaRajapakse** [comment]
I haven't checked it yet. I'll update it to work with Transformers 2.2 tonight. Thanks for the update!

**Comment by ThilinaRajapakse** [comment]
Should be fixed now in 0.8.0. Please do let me know if anything is behaving. I can't run full tests atm as my GPU is otherwise engaged. :sweat_smile:
