### ISSUE TITLE
support for python 3.10

### ISSUE THREAD

**Issue by luketudge** [ThilinaRajapakse/simpletransformers#1426]
**Describe the bug**

Python 3.10 is not currently supported. The removal of some abstract base classes from `collections` [in 3.10](https://docs.python.org/3/whatsnew/3.10.html#removed) is the only breaking change I have found so far (was noted in #1386 ).

**To Reproduce**

For example:

```
virtualenv --python==3.10 .venv
source .venv/bin/activate
pip install simpletransformers
python
```
```python
from simpletransformers import classification
```
```
ImportError: cannot import name 'Iterable' from 'collections'
```

**Expected behavior**

Either pip should fail to install simpletransformers on >=3.10 or the import of `classification` should succeed.

**Suggestions**

If support for 3.10 is not a priority yet, just change setup.py [here](https://github.com/ThilinaRajapakse/simpletransformers/blob/40cb71c04696e58fc6eefabe5ecb3a7cc1d3579d/setup.py#L23). Otherwise it looks as though changes are needed in:

* focal_loss.py [here](https://github.com/ThilinaRajapakse/simpletransformers/blob/fe70794cdc2c19808ff3b65155862f08fee86e79/simpletransformers/losses/focal_loss.py#L2)
* ner_utils.py [here](https://github.com/ThilinaRajapakse/simpletransformers/blob/f15ef8cd1ce3c3ed2319009f6106a0c71abb72a6/simpletransformers/ner/ner_utils.py#L20), [here](https://github.com/ThilinaRajapakse/simpletransformers/blob/f15ef8cd1ce3c3ed2319009f6106a0c71abb72a6/simpletransformers/ner/ner_utils.py#L756), and [here](https://github.com/ThilinaRajapakse/simpletransformers/blob/f15ef8cd1ce3c3ed2319009f6106a0c71abb72a6/simpletransformers/ner/ner_utils.py#L760)
* classification_utils.py [here](https://github.com/ThilinaRajapakse/simpletransformers/blob/f15ef8cd1ce3c3ed2319009f6106a0c71abb72a6/simpletransformers/classification/classification_utils.py#L25), [here](https://github.com/ThilinaRajapakse/simpletransformers/blob/f15ef8cd1ce3c3ed2319009f6106a0c71abb72a6/simpletransformers/classification/classification_utils.py#L1002), and [here](https://github.com/ThilinaRajapakse/simpletransformers/blob/f15ef8cd1ce3c3ed2319009f6106a0c71abb72a6/simpletransformers/classification/classification_utils.py#L1006)

**Comment by luketudge** [comment]
fixed in #1427
