### ISSUE TITLE
Cannot import name 'BertweetTokenizer'

### ISSUE THREAD

**Issue by josejuanmartinez** [ThilinaRajapakse/simpletransformers#775]
**Describe the bug**
Today simpletransformers==0.48.14 stopped working for me. It just throws an error when importing either ClassificationArgs or Classificationmodel due to the lack of BertweetTokenizer, which I'm not using at all.

![image](https://user-images.githubusercontent.com/36634572/96428916-9db33700-1200-11eb-81ee-8d25f371b70e.png)

**To Reproduce**
With simpletransformers==0.48.14, just execute:

`from simpletransformers.classification import ClassificationArgs`

**Expected behavior**
Import should work with no error.

**Screenshots**
![image](https://user-images.githubusercontent.com/36634572/96428916-9db33700-1200-11eb-81ee-8d25f371b70e.png)

**Desktop (please complete the following information):**
 - Unix

**More info**
It works in 0.48.0, for example.

**Comment by ThilinaRajapakse** [comment]
Updating `transformers` should fix this.

**Comment by josejuanmartinez** [comment]
Ok thank you so much!
